apiVersion: v1
description: Spade Helm Chart
name: spade
type: application
version: 0.2.0
appVersion: 0.1.0
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 15.2.5
    condition: postgresql.enabled
