docker:
  spade:
    image: ghcr.io/crugroup/spadekit
    tag: latest
  spadeUI:
    image: ghcr.io/crugroup/spadeui
    tag: latest


spade:
  env:
    - name: foo
      externalSecret: false
      value: bar
    - name: baz
      externalSecret: true
      secretName: spade-secrets
      secretKey: qux
  django:
    adminUrl: admin/
    allowedHosts: ""
    collectFastStrategy: collectfast.strategies.filesystem.FileSystemStrategy
    settingsModule: config.settings.production
    ssl:
      redirect: False
    secretKey:
      externalSecret: false
      value: Srxt2kGXi0ErSF1ApgK5ZJyMDNHyetTLbaa67tPitMtl9cdpkwnDTTDZCjsGDlIO
    fieldEncryptionKey:
      externalSecret: true
      secretName: spade-secrets
      secretKey: django-field-encryption-key

  pullPolicy: Always
  priorityClassName: ""
  nodeSelector: {}
  affinity: {}
  tolerations: []
  resources: {}
  replicas: 1
  revisionHistoryLimit: 3
  podDisruptionBudget:
    enabled: false
    config:
      maxUnavailable: 1


spadeUI:
  env: []
  pullPolicy: Always
  priorityClassName: ""
  nodeSelector: {}
  affinity: {}
  tolerations: []
  resources: {}
  replicas: 1
  revisionHistoryLimit: 3
  podDisruptionBudget:
    enabled: false
    config:
      maxUnavailable: 1

ingress:
  className: nginx
  spade:
    path: "/"
    host: backend
    annotations: {}
  spadeUI:
    path: "/"
    host: frontend
    annotations: {}

postgresql:
  enabled: false
  postgresHost: postgresql
  auth:
    username: spade
    database: spade
    password:
      externalSecret: false
      value: 3zLFpL6PVRHtBL91rM6ST24faVJU8a6z

  service:
    port: 5432
