apiVersion: apps/v1
kind: Deployment
metadata:
  name: spade
  labels:
    app: {{ template "spade.name" . }}
    component: spade
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.spade.replicas }}
  revisionHistoryLimit: {{ .Values.spade.revisionHistoryLimit }}
  strategy: {}
  selector:
    matchLabels:
      app: {{ template "spade.name" . }}
  template:
    metadata:
      annotations:
        checksum/spade-configmap: {{ include (print $.Template.BasePath "/django-configmap.yaml") . | sha256sum }}
      labels:
        app: {{ template "spade.name" . }}
        component: spade
        release: {{ .Release.Name }}
        {{- range $setting, $option := .Values.spade.labels }}
        {{ $setting | quote }}: {{ $option | quote }}
        {{- end }}
    spec:
      containers:
        - args:
            - start
          envFrom:
            - configMapRef:
                name: "{{ template "spade.name" . }}-env"
          env:
{{ include "spade.env" . | indent 12 }}
          image: {{ template "spade.image" . }}
          imagePullPolicy: {{ .Values.spade.pullPolicy }}
          name: spade
          tty: true
          stdin: true
          ports:
            - name: spade
              containerPort: 5000
              protocol: TCP
          resources:
{{ toYaml .Values.spade.resources | indent 12 }}
      initContainers:
        - args:
            - migrate
          envFrom:
            - configMapRef:
                name: "{{ template "spade.name" . }}-env"
          env:
{{ include "spade.env" . | indent 12 }}
          image: {{ template "spade.image" . }}
          imagePullPolicy: {{ .Values.spade.pullPolicy }}
          name: spade-init
          tty: true
          stdin: true
          ports:
            - name: spade
              containerPort: 5000
              protocol: TCP
          resources:
{{ toYaml .Values.spade.resources | indent 12 }}
      restartPolicy: Always
      {{- if .Values.spade.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.spade.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.spade.affinity }}
      affinity:
{{ toYaml .Values.spade.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.spade.tolerations }}
      tolerations:
{{ toYaml .Values.spade.tolerations | indent 8 }}
      {{- end }}
      priorityClassName: {{ .Values.spade.priorityClassName | quote }}
status: {}
