{{- if .Values.spade.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "spade.name" . }}-pdb
spec:
  {{- toYaml .Values.spade.podDisruptionBudget.config | nindent 2 }}
  selector:
    matchLabels:
      component: spade
{{- end }}
