apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "spade.name" . }}-env"
  labels:
    app: spade
data:
  POSTGRES_HOST: {{ include "spade.postgresql.host" . | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  POSTGRES_PORT: {{ .Values.postgresql.service.port | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  {{- if not .Values.postgresql.auth.password.externalSecret }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password.value | quote }}
  {{- end }}
  DJANGO_ADMIN_URL: {{ .Values.spade.django.adminUrl | quote }}
  DJANGO_ALLOWED_HOSTS: {{ include "spade.django.allowedHosts" . | quote }}
  FRONTEND_EXTERNAL_URL: {{ printf "https://%s" .Values.ingress.spadeUI.host | quote }}
  DJANGO_COLLECTFAST_STRATEGY: {{ .Values.spade.django.collectFastStrategy | quote }}
  {{- if not .Values.spade.django.secretKey.externalSecret }}
  DJANGO_SECRET_KEY: {{ .Values.spade.django.secretKey.value | quote }}
  {{- end }}
  DJANGO_SETTINGS_MODULE: {{ .Values.spade.django.settingsModule | quote }}
  DJANGO_SECURE_SSL_REDIRECT: {{ .Values.spade.django.ssl.redirect | quote }}
  DJANGO_SITE_DOMAIN: {{ .Values.ingress.spadeUI.host | quote }}
  {{- if not .Values.spade.django.fieldEncryptionKey.externalSecret }}
  FIELD_ENCRYPTION_KEY: {{ .Values.spade.django.fieldEncryptionKey.value | quote }}
  {{- end }}
  {{- range $setting, $option := .Values.environment }}
  {{ $setting }}: {{ $option | quote }}
  {{- end }}
