apiVersion: apps/v1
kind: Deployment
metadata:
  name: spade
  labels:
    app: {{ template "spade.name" . }}
    component: spade
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.worker.replicas }}
  strategy: {}
  selector:
    matchLabels:
      app: {{ template "spade.name" . }}
  template:
    metadata:
      annotations:
        checksum/spade-configmap: {{ include (print $.Template.BasePath "/django-configmap.yaml") . | sha256sum }}
      labels:
        app: {{ template "spade.name" . }}
        component: spade
        release: {{ .Release.Name }}
    spec:
      containers:
      - args:
        - /start
        envFrom:
          - configMapRef:
              name: "{{ template "spade.name" . }}-env"
        env:
          {{- if .Values.postgresql.auth.password.externalSecret }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresql.auth.password.secretName | quote }}
                key: {{ .Values.postgresql.auth.password.secretKey | quote }}
          {{- end }}
          {{- if .Values.spade.django.secretKey.externalSecret }}
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.spade.django.secretKey.secretName | quote }}
                key: {{ .Values.spade.django.secretKey.secretKey | quote }}
          {{- end }}
          {{- if .Values.spade.django.fieldEncryptionKey.externalSecret }}
          - name: FIELD_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.spade.django.fieldEncryptionKey.secretName | quote }}
                key: {{ .Values.spade.django.fieldEncryptionKey.secretKey | quote }}
          {{- end }}
          {{- range .Values.spade.env }}
          - name: {{ .name }}
            {{- if .externalSecret }}
            valueFrom:
              secretKeyRef:
                name: {{ .secretName | quote }}
                key: {{ .secretKey | quote }}
            {{- else }}
            value: {{ .value | quote }}
            {{- end }}
          {{- end }}
        image: {{ template "spade.image" . }}
        imagePullPolicy: {{ .Values.spade.pullPolicy }}
        name: spade
        tty: true
        stdin: true
        ports:
        - name: spade
          containerPort: 5000
          protocol: TCP
        resources:
{{ toYaml .Values.spade.resources | indent 10 }}
      restartPolicy: Always
      {{- if .Values.spade.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.spade.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.spade.affinity }}
      affinity:
{{ toYaml .Values.spade.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.spade.tolerations }}
      tolerations:
{{ toYaml .Values.spade.tolerations | indent 8 }}
      {{- end }}
      priorityClassName: {{ .Values.spade.priorityClassName | quote }}
status: {}
