apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "spade.name" . }}-ui-env"
  labels:
    app: "{{ template "spade.name" . }}-ui"
data:
  VITE_BACKEND_BASE_URL: "{{ .Values.spade.django.apiUrl }}"
  {{- range $setting, $option := .Values.environment }}
  {{ $setting }}: "{{ $option }}"
  {{- end }}
