apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "spade.name" . }}-ui-env"
  labels:
    app: spade-ui
data:
  {{- range $setting, $option := .Values.environment }}
  {{ $setting }}: "{{ $option }}"
  {{- end }}
