apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ template "spade.name" . }}-ui"
  labels:
    app: {{ template "spade.name" . }}
    component: "{{ template "spade.name" . }}-ui"
    release: {{ .Release.Name }}
  annotations:
    {{ range $key, $value := .Values.ingress.spadeUI.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.spadeUI.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: spade-ui
                port: 
                  name: ui
      host: {{ .Values.ingress.spadeUI.host }}
  tls:
    - hosts:
        - spade-dev.crugroup.com
      secretName: spade-tls
